path=($HOME/.rbenv/bin /usr/local/bin $HOME/bin $HOME/Applications/scripts $path)
path=(/usr/local/lib/luarocks/bin $path)
path=($path /usr/local/mysql/bin/ /usr/texbin /usr/sfw/bin /usr/ccs/bin)
path=($path /usr/sbin /usr/local/Cellar/python/2.7.1/bin/ /usr/local/lib/luarocks/bin)
path=($path /usr/local/lib/luarocks/bin)
