path=($HOME/.rbenv/bin /usr/local/bin $HOME/Applications/scripts $path)
path=($path /usr/texbin)
path=($path /usr/local/Cellar/python/2.7.1/bin/ /usr/local/lib/luarocks/bin)
path=($path /usr/local/Cellar/chicken/4.7.0/bin)
path=($path /usr/local/mercury-11.07-beta-2011-12-16/bin)
path=($path ~/.local/bin)
