alias c='clear'
alias cvim='mvim -v'
alias vv='vi ~/.vimrc'
alias ls='ls -G -a '
alias ll="ls -al"
alias cls='clear; ls'
alias fd=pushd
alias sd=popd
alias sess='tmux attach-session -t'
alias lvim='~/.local/bin/vim'
